stages:
  - build
  - test

build-binaries:
  image: dbogatov/docker-images:pbc-latest
  stage: build
  script:
    - cd ./path-oram
    - make binaries
  artifacts:
    expire_in: 30 min
    paths:
      - ./path-oram/bin
  tags:
    - docker

build-docs:
  image: dbogatov/docker-images:doxygen-latest
  stage: build
  script:
    - cd ./path-oram
    - doxygen ../Doxyfile
  artifacts:
    expire_in: 30 min
    paths:
      - ./docs
      - Dockerfile
      - nginx.conf
  tags:
    - docker

unit-test:
  image: dbogatov/docker-images:pbc-latest
  stage: test
  script:
    - cd ./path-oram/
    - make coverage
  dependencies: []
  artifacts:
    expire_in: 1 day
    paths:
      - ./path-oram/coverage-html/
  tags:
    - docker

integration-test:
  image: dbogatov/docker-images:pbc-latest
  stage: test
  script:
    - cd ./path-oram/
    - make run-integration
  dependencies: []
  tags:
    - docker

benchmarks:
  image: dbogatov/docker-images:pbc-latest
  stage: test
  script:
    - cd ./path-oram/
    - make run-benchmarks
  dependencies: []
  tags:
    - docker

shared-library:
  image: dbogatov/docker-images:pbc-latest
  stage: test
  script:
    - cd ./path-oram/
    - make shared ldconfig run-shared-lib
  dependencies: []
  tags:
    - docker
