stages:
- build
- test

build-binaries:
  image: dbogatov/docker-images:pbc-latest
  stage: build
  script:
  - cd ./path-oram
  - make binaries
  artifacts:
    expire_in: 30 min
    paths:
    - ./path-oram/bin
  tags:
  - docker

build-docs:
  image: dbogatov/docker-images:doxygen-latest
  stage: build
  script:
  - cd ./path-oram
  - doxygen ../Doxyfile
  artifacts:
    expire_in: 30 min
    paths:
    - ./docs
    - Dockerfile
    - nginx.conf
  tags:
  - docker

test:
  image: dbogatov/docker-images:pbc-latest
  stage: test
  script:
  - cd ./path-oram/
  - make bin/main
  - ./bin/main
  - make coverage
  dependencies:
    - build-binaries
  artifacts:
    expire_in: 1 day
    paths:
      - ./path-oram/coverage-html/
  tags:
  - docker
